export const ADD_INGREDIENT = "ADD_INGREDIENT"
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT"
export const UPDATE_PARTCH = "UPDATE_PARTCH"
export const RESET = "RESET"
export const LOAD_ORDERS = "LOAD_ORDERS"
export const ORDER_LOAD_FAILED = "ORDER_LOAD_FAILED"


//AUTH TYPES 
export const AUTH_SUCCESS = "AUTH_SUCCESS"
export const AUTH_FAILED = "AUTH_FAILED"
export const AUTH_LOADING = "AUTH_LOADING"
export const AUTH_LOGOUT = "AUTH_LOGOUT"